kind: Deployment
apiVersion: apps/v1
metadata:
  name: electric-humvee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electric-humvee
  template:
    metadata:
      labels:
        app: electric-humvee
    spec:
      containers:
        - name: electric-humvee
          image: theinfamousrj/electric-humvee
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: electric-humvee
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: electric-humvee
